/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-secondary-fixed-variant': '#0c5216',
        'surface-bright': '#f4faff',
        'on-tertiary': '#ffffff',
        'surface-dim': '#cbdde7',
        outline: '#707a6c',
        'inverse-primary': '#88d982',
        'secondary-container': '#acf4a4',
        'surface-container-lowest': '#ffffff',
        'on-tertiary-container': '#c7ffc5',
        'tertiary-fixed-dim': '#90d792',
        'on-tertiary-fixed': '#002107',
        'primary-container': '#2e7d32',
        error: '#ba1a1a',
        tertiary: '#1d622b',
        'surface-tint': '#1b6d24',
        'on-secondary-container': '#307231',
        'on-background': '#0d1e25',
        'on-primary-container': '#cbffc2',
        'surface-container-highest': '#d4e5ef',
        'on-secondary-fixed': '#002203',
        'on-secondary': '#ffffff',
        'on-error-container': '#93000a',
        primary: '#0d631b',
        secondary: '#2a6b2c',
        surface: '#f4faff',
        'outline-variant': '#bfcaba',
        'primary-fixed-dim': '#88d982',
        'tertiary-fixed': '#abf4ac',
        'inverse-surface': '#23333a',
        'on-surface': '#0d1e25',
        'secondary-fixed': '#acf4a4',
        'inverse-on-surface': '#e2f3fd',
        'on-primary-fixed-variant': '#005312',
        'surface-variant': '#d4e5ef',
        'surface-container': '#dff1fb',
        'primary-fixed': '#a3f69c',
        'secondary-fixed-dim': '#91d78a',
        'surface-container-low': '#e7f6ff',
        'on-tertiary-fixed-variant': '#07521d',
        'on-surface-variant': '#40493d',
        background: '#f4faff',
        'surface-container-high': '#d9ebf5',
        'on-primary': '#ffffff',
        'tertiary-container': '#387b41',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-primary-fixed': '#002204',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Work Sans', 'sans-serif'],
        label: ['Work Sans', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
